### ISSUE TITLE
Setting firewall rules to null, as shown in the example, results in NPE

### ISSUE THREAD

**Issue by patelrit** [profitbricks/profitbricks-sdk-java#10]
Setting firewall rules to null, as shown in the example, results in NPE

Code:
	        nic.getEntities().setFirewallrules(null);

Exception:

java.lang.NullPointerException: null
	at com.profitbricks.rest.domain.Helper.convertFirewallRules(Helper.java:142) ~[profitbricks-sdk-java-1.0.jar:na]
	at com.profitbricks.rest.domain.Helper.convertNic(Helper.java:134) ~[profitbricks-sdk-java-1.0.jar:na]
	at com.profitbricks.sdk.NicApi.createNic(NicApi.java:51) ~[profitbricks-sdk-java-1.0.jar:na]

**Comment by baldwinSPC** [comment]
@patelrit This should be corrected.

**Comment by baldwinSPC** [comment]
@patelrit I'm going to go ahead and close it, please re-open if it doesn't pan out. ;) Thanks for reporting it!
