### ISSUE TITLE
JsonMappingException when trying to retrieve all services 

### ISSUE THREAD

**Issue by patelrit** [profitbricks/profitbricks-sdk-java#8]
We are seeing the following error when trying to retrieve all services via the java api. 

com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of boolean out of START_OBJECT token

 at [Source: {

  "id" : "18a64611-2a36-4d25-8dfc-4bb335e40303/servers",

  "type" : "collection",

  "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers",

  "items" : [ {

    "id" : "c487e133-977c-4baa-8559-97c36beb10a3",

    "type" : "server",

    "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3",

    "metadata" : {

      "createdDate" : "2015-07-10T19:40:07Z",

      "createdBy" : "ritesh@nirmata.com",

      "etag" : "7c3928853109b482153dc7e89481b7e9",

      "lastModifiedDate" : "2015-07-23T01:24:36Z",

      "lastModifiedBy" : "ritesh@nirmata.com",

      "state" : "AVAILABLE"

    },

    "properties" : {

      "name" : "test",

      "cores" : 2,

      "ram" : 4096,

      "availabilityZone" : "AUTO",

      "vmState" : "RUNNING",

      "bootCdrom" : null,

      "bootVolume" : {

        "id" : "837c7498-8485-48bd-8352-e74a1db1ee96",

        "type" : "volume",

        "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/volumes/837c7498-8485-48bd-8352-e74a1db1ee96",

        "metadata" : {

          "createdDate" : "2015-07-10T19:52:21Z",

          "createdBy" : "ritesh@nirmata.com",

          "etag" : "e5c65c674f04a47e6e3b262b25059578",

          "lastModifiedDate" : "2015-07-10T19:52:21Z",

          "lastModifiedBy" : "ritesh@nirmata.com",

          "state" : "AVAILABLE"

        },

        "properties" : {

          "name" : "hdd",

          "type" : "HDD",

          "size" : 10,

          "image" : "4ddd65dd-1fa8-11e5-91f8-52540066fee9",

          "imagePassword" : null,

          "bus" : "VIRTIO",

          "licenceType" : "LINUX",

          "cpuHotPlug" : true,

          "cpuHotUnplug" : false,

          "ramHotPlug" : true,

          "ramHotUnplug" : false,

          "nicHotPlug" : true,

          "nicHotUnplug" : true,

          "discVirtioHotPlug" : true,

          "discVirtioHotUnplug" : true,

          "discScsiHotPlug" : false,

          "discScsiHotUnplug" : false,

          "deviceNumber" : 2

        }

      }

    },

    "entities" : {

      "cdroms" : {

        "id" : "c487e133-977c-4baa-8559-97c36beb10a3/cdroms",

        "type" : "collection",

        "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3/cdroms",

        "items" : [ ]

      },

      "volumes" : {

        "id" : "c487e133-977c-4baa-8559-97c36beb10a3/volumes",

        "type" : "collection",

        "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3/volumes",

        "items" : [ {

          "id" : "837c7498-8485-48bd-8352-e74a1db1ee96",

          "type" : "volume",

          "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/volumes/837c7498-8485-48bd-8352-e74a1db1ee96",

          "metadata" : {

            "createdDate" : "2015-07-10T19:52:21Z",

            "createdBy" : "ritesh@nirmata.com",

            "etag" : "e5c65c674f04a47e6e3b262b25059578",

            "lastModifiedDate" : "2015-07-10T19:52:21Z",

            "lastModifiedBy" : "ritesh@nirmata.com",

            "state" : "AVAILABLE"

          },

          "properties" : {

            "name" : "hdd",

            "type" : "HDD",

            "size" : 10,

            "image" : "4ddd65dd-1fa8-11e5-91f8-52540066fee9",

            "imagePassword" : null,

            "bus" : "VIRTIO",

            "licenceType" : "LINUX",

            "cpuHotPlug" : true,

            "cpuHotUnplug" : false,

            "ramHotPlug" : true,

            "ramHotUnplug" : false,

            "nicHotPlug" : true,

            "nicHotUnplug" : true,

            "discVirtioHotPlug" : true,

            "discVirtioHotUnplug" : true,

            "discScsiHotPlug" : false,

            "discScsiHotUnplug" : false,

            "deviceNumber" : 2

          }

        } ]

      },

      "nics" : {

        "id" : "c487e133-977c-4baa-8559-97c36beb10a3/nics",

        "type" : "collection",

        "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3/nics",

        "items" : [ {

          "id" : "a16ddb6b-4980-42e5-8169-abb3e5568155",

          "type" : "nic",

          "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3/nics/a16ddb6b-4980-42e5-8169-abb3e5568155",

          "metadata" : {

            "createdDate" : "2015-07-10T19:42:27Z",

            "createdBy" : "ritesh@nirmata.com",

            "etag" : "b03c54a3fbba9664100d4b1234bbcf3d",

            "lastModifiedDate" : "2015-07-11T01:42:42Z",

            "lastModifiedBy" : "ritesh@nirmata.com",

            "state" : "AVAILABLE"

          },

          "properties" : {

            "name" : null,

            "mac" : "02:01:b2:28:ce:ca",

            "ips" : [ "10.8.82.11", "192.152.28.61" ],

            "dhcp" : true,

            "lan" : 2,

            "firewallActive" : false

          },

          "entities" : {

            "firewallrules" : {

              "id" : "a16ddb6b-4980-42e5-8169-abb3e5568155/firewallrules",

              "type" : "collection",

              "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3/nics/a16ddb6b-4980-42e5-8169-abb3e5568155/firewallrules",

              "items" : [ {

                "id" : "2724be41-c3d1-4ba2-8492-f0c4789b6135",

                "type" : "firewall-rule",

                "href" : "https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/servers/c487e133-977c-4baa-8559-97c36beb10a3/nics/a16ddb6b-4980-42e5-8169-abb3e5568155/firewallrules/2724be41-c3d1-4ba2-8492-f0c4789b6135",

                "metadata" : {

                  "createdDate" : "2015-07-10T19:46:54Z",

                  "createdBy" : "ritesh@nirmata.com",

                  "etag" : "6648194656adaf6ad653a7c02e343b75",

                  "lastModifiedDate" : "2015-07-10T19:46:54Z",

                  "lastModifiedBy" : "ritesh@nirmata.com",

                  "state" : "AVAILABLE"

                },

                "properties" : {

                  "name" : "Unnamed Rule",

                  "protocol" : "ANY",

                  "sourceMac" : null,

                  "sourceIp" : null,

                  "targetIp" : "192.96.159.216",

                  "icmpCode" : null,

                  "icmpType" : null,

                  "portRangeStart" : null,

                  "portRangeEnd" : null

                }

              } ]

            }

          }

        } ]

      }

    }

  } ]

}; line: 23, column: 25] (through reference chain: com.profitbricks.rest.domain.raw.ServersRaw["items"]->com.profitbricks.rest.domain.raw.ServerRaw["properties"]->com.profitbricks.rest.domain.raw.Properties["bootVolume"])

at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseBoolean(StdDeserializer.java:204) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:163) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:145) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:209) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.impl.InnerClassProperty.deserializeAndSet(InnerClassProperty.java:102) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:232) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2146) ~[jackson-databind-2.4.1.2.jar:2.4.1.2]

at com.profitbricks.rest.client.AbstractRestClient.bindObject(AbstractRestClient.java:97) ~[profitbricks-sdk-java-1.0.jar:na]

at com.profitbricks.rest.client.RestClient.get(RestClient.java:77) ~[profitbricks-sdk-java-1.0.jar:na]

at com.profitbricks.rest.client.RestClient.get(RestClient.java:103) ~[profitbricks-sdk-java-1.0.jar:na]

at com.profitbricks.sdk.ServerApi.getAllServers(ServerApi.java:39) ~[profitbricks-sdk-java-1.0.jar:na]

at com.nirmata.profitbricks.ProfitBricksProvider.getInstances(ProfitBricksProvider.java:87) [bin/:na]

at com.nirmata.profitbricks.ProfitBricksProvider.main(ProfitBricksProvider.java:373) [bin/:na]

**Comment by jasminSPC** [comment]
We've found the issue and after testing the library it will be released.

**Comment by baldwinSPC** [comment]
@patelrit We patched the library to address this issue. You'll want to update your library with the latest code we just pushed. Let me know if this resolves the issue. Tnx.

**Comment by baldwinSPC** [comment]
@patelrit @jasminSPC I'm going to go ahead and close this issue.
